app_newspaper/accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/',     SignUpView.as_view(), name='signup'),
]

app_newspaper/app_newspaper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler403
from django.views.generic.base import TemplateView
from articles.views import Error403View


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('', include('articles.urls')),
    path('', include('pages.urls')),
]

handler403 = Error403View.as_view()

app_newspaper/articles/urls.py
from django.urls import path
from .views import (
      ArticleListView,
      ArticleDetailView, 
      ArticleDeleteView,
      ArticleUpdateView,
      ArticleCreateView,
) 

urlpatterns = [
    path("<int:pk>/", ArticleDetailView.as_view(), name="article_detail"),
    path("<int:pk>/edit/", ArticleUpdateView.as_view(), name="article_edit"),
    path("<int:pk>/delete/", ArticleDeleteView.as_view(), name="article_delete"),
    path("new/", ArticleCreateView.as_view(), name="article_new"),
    path('', ArticleListView.as_view(), name='article_list'),

]

app_newspaper/pages/urls.py
from django.urls import path
from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

app_newspaper/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class CustomUser(AbstractUser):
    age= models.PositiveBigIntegerField(null=True, blank=True)

app_newspaper/articles/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# Create your models here.

class Article (models.Model):
    title= models.CharField(max_length=255)
    body= models.TextField()
    date= models.DateTimeField(auto_now_add=True)
    author= models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete= models.CASCADE,
    )
    def __str__(self) :
        return self.title
    
    def get_absolute_url(self):
        return reverse("article_detail", kwargs={"pk": self.pk})

class Comment(models.Model): #new
    article = models.ForeignKey(Article,
        on_delete= models.CASCADE,
        )
    comment = models.CharField(
        max_length=140
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete= models.CASCADE,
    )

    def __str__(self) :
        return self.comment

    def get_absolute_url(self):
        return reverse("article_list")
    

app_newspaper/pages/models.py
from django.db import models

# Create your models here.

app_newspaper/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
class CustomUseCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model= CustomUser
        fields=(
            'username',
            'email',
            'age',
        )

class CustomUseChangeForm(UserChangeForm):
    class Meta:
        model= CustomUser
        fields=(
            'username',
            'email',
            'age',
        )

app_newspaper/articles/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model= Comment
        fields= ("comment",)

app_newspaper/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from accounts.forms import CustomUseCreationForm

# Create your views here.
class SignUpView(CreateView):
    form_class= CustomUseCreationForm
    success_url= reverse_lazy('login')
    template_name="registration/signup.html"

app_newspaper/articles/views.py
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import View
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.shortcuts import render
from django.views.generic import(
    View,
    TemplateView,
    ListView,
    DetailView
)


from .forms import CommentForm
from .models import Article

# Create your views here.
class ArticleListView(LoginRequiredMixin,ListView):
    model= Article
    template_name ="article_list.html"

class CommentGet(LoginRequiredMixin, DetailView):
    model = Article
    template_name = "article_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context

class CommentPost(SingleObjectMixin,LoginRequiredMixin, FormView):
    model = Article
    form_class = CommentForm
    template_name = "article_detail.html"
    success_url = reverse_lazy("article_list")

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.author = self.request.user
        comment = form.save(commit = False)
        comment.article = self.object
        comment.save()
        return super().form_valid(form)


class ArticleDetailView(LoginRequiredMixin, View):
    def get(self, request, *args,**kwargs):
        view= CommentGet.as_view()
        return view(request, *args, **kwargs)
    
    def post(self, request, *args,**kwargs):
        view= CommentPost.as_view()
        return view(request, *args, **kwargs)


class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin,UpdateView):
    model= Article
    fields = (
        "title",
        "body",
    )
    template_name ="article_edit.html"

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin,DeleteView):
    model= Article
    template_name ="article_delete.html"
    success_url = reverse_lazy("article_list") ##funcion que será llamada al final 

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

class ArticleCreateView(LoginRequiredMixin, CreateView):
    model= Article
    template_name ="article_new.html"
    fields = (
        "title",
        "body",
    )
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class Error403View(TemplateView):
    template_name = "errorScreens/error_403.html"

app_newspaper/pages/views.py
from turtle import home
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class HomePageView(TemplateView):
    template_name= "home.html"
    

app_newspaper/templates/article_delete.html
{%extends "base.html"%}




{% block content %}
    <h1>Eliminar</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ article.title }}"?</p>
        <button class="btn btn-danger ml-2" type="submit" > Confirmar </button>
    </form>
{% endblock content %}

app_newspaper/templates/article_detail.html
{%extends "base.html"%}

{%load crispy_forms_tags%}
{%block content%}
   <div class= "article-entry">
        <h2>{{ object.title }}</h2>
        <p>by {{ object.author }} | {{object.date }}</p>
        <p>{{ object.body }}</p>
   </div>
   <hr>
   <h4>Comentarios</h4>
   
   {% for comment in article.comment_set.all%}
        <p>{{comment.author}} &middot; {{comment}} </p>
    {%endfor%}
   <hr>
   <h4>Agregar Comentario</h4>
   <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <div style="text-align: right">
          <button class="btn btn-info"  type="submit" > Guardar </button>
        </div>
    </form>
    <div style="text-align: center">
     <p><a href="{% url 'article_edit' article.pk %}" class="btn btn-outline-success">Editar</a> |
     <a href="{% url 'article_delete' article.pk %}" class="btn btn-outline-danger">Eliminar</a></p>
     <p>De regreso <a href="{% url 'article_list'%}" class="text-info">Todos los artículos</a></p>
   </div>

{%endblock content%}

app_newspaper/templates/article_edit.html
{%extends "base.html"%}
{%load crispy_forms_tags%}



{% block content %}
    <h1>Editar</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <div style="text-align: right">
            <button class="btn btn-info" type="submit" >Actualizar</button>
        </div>
    </form>
{% endblock content %}

app_newspaper/templates/article_list.html
{%extends "base.html"%}


{% block title %}Articles{% endblock title %}

{% block content %}
    {% for article in article_list %}
       <div class="card">
            <div class="card-header">
                <span class="navbar-brand mb-0 h1">
                    {{article.title}}
                </span> &middot;
                <span class="text-muted"> by {{article.author}} | {{article.date}} </span>
            </div>
            <div class="card-body">
                <p>{{article.body}}</p>
                <a href="{% url 'article_edit' article.pk %}" class="btn btn-outline-success">Editar</a>
                <a href="{% url 'article_delete' article.pk %}" class="btn btn-outline-danger">Eliminar</a>
                <a href="{% url 'article_detail' article.pk %}" class="btn btn-outline-success">Comentar</a>
            </div>
            <div class="card-footer ">
                {% for comment in article.comment_set.all %}
                    <p class="text-muted">
                        <span class="text-dark">
                            {{comment.author}} &middot;
                        </span>
                        {{comment}}
                    </p>
                {%endfor%}
            </div>
       </div>  
       <br/>   
    {% endfor %}
{% endblock content %}

app_newspaper/templates/article_new.html
{%extends "base.html"%}
{%load crispy_forms_tags%}



{% block content %}
    <h1>Nuevo Artículo</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <div style="text-align: right">
         <button class="btn btn-info"  type="submit" > Guardar </button>
        </div>
    </form>
{% endblock content %}

app_newspaper/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width-device-width,
            initial-scale=1, shrink-to-fit-no"> 
        <title>{% block title %} Newspaper App {% endblock title%}</title>
        <link rel="stylesheet" href= "{% static 'css/base.css'%}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <header class="p-4 mb-4 border-bottom">
                <div class="p-3 mb-2 bg-secondary text-white">
                    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                        <a class="navbar-brand mb-0 h1" href="{% url 'home' %}">Newspaper</a>
                        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                        {% if user.is_authenticated%}
                                <li><a href="{% url 'article_new' %}" class="navbar-brand mb-0 h1"> + New</a></li>
                            </ul>
                            <div class="dropdown text-end">
                                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle"
                                    id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ user.username}}
                                </a>
                                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                                    <li><a class="dropdown-item" href="{% url 'password_change' %}">
                                      Cambia la contraseña  </a></li>
                                    <li><a class="dropdown-item" href="{% url 'logout' %}">
                                       Cerrar Sesion</a></li>

                                </ul>
                            </div>
                        {% else %}
                            </ul>
                            <div class="text end">
                                <a href="{% url 'login' %}" class="btn btn-outline-info">
                                    Iniciar sesión </a>
                                <a href="{% url 'signup' %}" class="btn btn-info">
                                    Inscribirse </a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </header>
        
            <main>
                {%block content%}
                {%endblock content%}
            </main>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </body>
</html>

app_newspaper/templates/errorScreens/error_403.html
{% extends "base.html" %}

{% block title %}ERROR{% endblock title %}
{% block content %}
<div class="error">
<h1>No puedes modificar este articulo!!</h1>
<a href="{% url 'article_list' %}">Regresar a la pagina inicial</a>
</div>
{% endblock content %}

app_newspaper/templates/home.html
{%extends "base.html"%}

{%block title %}Home{%endblock title%}

{%block content%}
    {%if user.is_authenticated%}
        Hola {{user.username}}! Usted tiene {{user.age}} años.
        <p><a href="{%url 'logout'%}">Cerrar Sesión</a></p>
    {%else%}
        <p>Usted no se ha identificado</p>
        <a href="{%url 'login'%}">Iniciar Sesión</a>
        <a href="{%url 'signup'%}">Inscribirse</a>
    {%endif%}
{%endblock content%}